[package]
name = "dystopia_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits"] }
proc-macro2 = "1.0"
proc-macro-crate = "3.1"
quote = "1.0"
