[package]
name = "dystopia_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
enum-map.workspace = true
rand.workspace = true
rand_distr.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
